language: csharp
solution: Duplicati.sln
install:
  - nuget restore Duplicati.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Duplicati.sln
  - mkdir ~/testdata
  - mkdir ~/testdata/data
  - mkdir ~/testdata/DSMCBE
  - wget "https://s3.amazonaws.com/duplicati-test-file-hosting/DSMCBE.zip"
  - wget "https://s3.amazonaws.com/duplicati-test-file-hosting/data.zip"
  - unzip -q DSMCBE.zip -d ~/testdata/
  - unzip -q data.zip -d ~/testdata/
  - chown -R travis ~/testdata/
  - chmod -R 755 ~/testdata
  - ls -la ~/testdata
  - ls -la ~/testdata/DSMCBE
  - ls -la ~/testdata/data
  - export USAGEREPORTER_Duplicati_LEVEL=none
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Duplicati/UnitTest/bin/Release/Duplicati.UnitTest.dll
